
# ---------------- MINI PROJECT USING THE CLOUDFORMATION-----------------------




AWSTemplateFormatVersion: '2010-09-09'
Description: Full Mini Architecture with ALB (2 AZ)

Parameters:

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select key pair

Resources:

# ---------------- VPC ----------------

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true

# ---------------- Subnets (2 AZs) ----------------

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

# ---------------- Internet Gateway ----------------

  IGW:
    Type: AWS::EC2::InternetGateway

  AttachIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

# ---------------- Routing ----------------

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  Route:
    Type: AWS::EC2::Route
    DependsOn: AttachIGW
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  RouteAssocA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref RouteTable

  RouteAssocB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref RouteTable

# ---------------- Security Group ----------------

  WebSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

# ---------------- EC2 Servers ----------------

  EC2A:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      SubnetId: !Ref SubnetA
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from Server A" > /var/www/html/index.html

  EC2B:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyPair
      SubnetId: !Ref SubnetB
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebSG
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "Hello from Server B" > /var/www/html/index.html

# ---------------- Load Balancer ----------------

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
      SecurityGroups:
        - !Ref WebSG
      Scheme: internet-facing

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      HealthCheckPath: /
      Targets:
        - Id: !Ref EC2A
        - Id: !Ref EC2B

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

# ---------------- Output ----------------

Outputs:

  LoadBalancerURL:
    Description: Open this URL in browser
    Value: !GetAtt ALB.DNSName

